### ISSUE TITLE
是不是还有train.tsv 到 tf_record的代码？提示找不到tf_record文件

### ISSUE THREAD

**Issue by gaoxuezhao** [ganguagua/error_recognize#1]
(0) Not found: ./output/train.tf_record; No such file or directory

**Comment by ganguagua** [comment]
data目录下生成train.tsv了吗，tf_record生成代码和训练代码在一起的

**Comment by gaoxuezhao** [comment]
> data目录下生成train.tsv了吗，tf_record生成代码和训练代码在一起的

找到了，git上的相关代码被注释了。

**Comment by ganguagua** [comment]
抱歉啊，我修改一下
